version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=test_pass
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=test_pass
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb
    ports:
      - "3307:3306"
    restart: unless-stopped

  moodle:
    image: docker.io/bitnami/moodle:4.5
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=test_pass
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_URL=http://localhost:8080
      - BITNAMI_DEBUG=true
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    restart: unless-stopped

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:
